### ISSUE TITLE
Request for dev and test set outputs

### ISSUE THREAD

**Issue by ruixilin** [kakaobrain/helo_word#1]
Hi guys,

I fear that I cannot reproduce your impressive results as mentioned in your paper. May I know if your team can share the dev and test set outputs please?

Thank you.

**Comment by yjchoe** [comment]
Hi @ruixilin,

Thanks for your interest in our work! We've uploaded our dev/test submissions [here](https://github.com/kakaobrain/helo_word/tree/master/bea2019submissions). 

You can also find all system submissions during the competition in the following link (uploaded by the organizers):
https://www.cl.cam.ac.uk/research/nl/bea2019st/data/system_output.bea9.tar.gz

**Comment by ruixilin** [comment]
Hi @yjchoe ,

Thank you so much for your help!
