### ISSUE TITLE
ModuleNotFoundError: No module named 'lm_scorer'

### ISSUE THREAD

**Issue by pohjie** [kakaobrain/helo_word#1]
This error arose from line 9 of spell.py- may I know how do I get this lm_scorer module? I've tried searching online but there is nothing on the lm_scorer module. Thank you.

**Comment by yjchoe** [comment]
Thanks for your interest in our work! It looks like our custom version of `fairseq` was somehow left out of the initial release. We'll work on this and release an updated version within the next few days.

**Comment by pohjie** [comment]
Sure thank you very much! I'm working on this research field for my Final Year Project in university- very excited to try and replicate your team's results! Thanks so much for releasing the code publicly too! :)

**Comment by yjchoe** [comment]
We've encountered an issue regarding our initial release, so we'll be removing this repository entirely and replace it with a new one. Please check out our new repo from https://github.com/kakaobrain within the next 24~48 hours. Thanks again for your interest!
