### ISSUE TITLE
ImportError: cannot import name 'LMScorer'

### ISSUE THREAD

**Issue by niucheney** [kakaobrain/helo_word#11]
Hi everyone,
When I ran preprocess.py, it gave me this error message.  I have installed lm_scorer package before I ran preprocess.py. But I found the calling procedure is different from ./gec/spell.py just like this link: https://github.com/simonepri/lm-scorer.  I wonder how to use LM_Scorer in this project and what's the version of lm_scorer or how to install lm_scorer. Can anyone help me? ^_^  
1. when I use "from lm_scorer import LMScorer" in ./gec/spell.py, the error message is as follows.
File "./gec/spell.py", line 8, in <module>
   from lm_scorer import LMScorer
ImportError: cannot import name 'LMScorer'
2. When I use "from lm_scorer.models.auto import AutoLMScorer as LMScorer" from https://github.com/simonepri/lm-scorer, the error message is as follows.
    File ".gec/spell.py", line36, in load_lm
        return LMScorer(args)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by niucheney** [comment]
Sorry, I forget to install fairseq

**Comment by MiaomiaoFu** [comment]
I have occured the same problem with you, how did u solve this problem? I have installed fairseq.

**Comment by niucheney** [comment]
Did you install fairseq in this project?
