### ISSUE TITLE
ImportError: cannot import name 'LMScorer'

### ISSUE THREAD

**Issue by MiaomiaoFu** [kakaobrain/helo_word#14]
When I run the preprocess.py, some errors occur.
Have anyone encountered with this problem?

**Comment by ksudoh** [comment]
It's probably due to the changes in lm-scorer.
In the current version, LMScorer is called by
`from lm_scorer.models.auto import AutoLMScorer as LMScorer`

https://pypi.org/project/lm-scorer/
