### ISSUE TITLE
Exception: Could not infer language pair, please provide it explicitly

### ISSUE THREAD

**Issue by pohjie** [kakaobrain/helo_word#2]
Thank you so much for taking the time to reupload your code for BEA 19 Shared Task! Unfortunately, while trying to run the command `python train.py --track 1 --train-mode pretrain --model base --ngpu 1`, I ran into the following error:

```
Traceback (most recent call last):
  File "/home/pohjie/anaconda3/envs/helo/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq_cli/train.py", line 407, in cli_main
    main(args)
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq_cli/train.py", line 39, in main
    task = tasks.setup_task(args)
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq/tasks/__init__.py", line 19, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args)
  File "/home/pohjie/beast19/helo_word/fairseq/fairseq/tasks/translation.py", line 109, in setup_task
    raise Exception('Could not infer language pair, please provide it explicitly')
Exception: Could not infer language pair, please provide it explicitly
```

I have tried my best to debug this to no avail. May I know what is a possible solution to this? Thank you.

**Comment by yjchoe** [comment]
Hi @pohjie ,

This probably means that the previous steps (either `preprocess.py` or `prepare.py`) was not done successfully or the preprocessed files were not found during training. fairseq is complaining that the preprocessed data does not have the correct form (parallel data files ending with `.ori-cor` extensions should be inside a `data-bin` directory). 

Can you double-check that all relevant data was downloaded and preprocessed correctly? You can post the logs you got from `preprocess.py` and `prepare.py` if you still encounter the problem. Thanks!

**Comment by pohjie** [comment]
Hi @yjchoe thanks so much! Indeed some files are empty- I am rerunning preprocess.py now. Can I clarify:

1. STEP 5-6 (wi-test) is commented out in preprocess.py. However, STEP 6-6 and 7-6 relies on wi-test. Should I comment out STEP 6-6 and 7-6 too?
2. STEP 6-11 and 7-11 relies on this file called jfleg. However, there is no mention of this file. Should I comment out these two steps too?

Thanks so much again!

**Comment by hammouse** [comment]
1. You should not comment out STEP 6-6 and 7-6. These steps check spell and tokenize the original part of wi test data.
2. We deleted 6-11 and 7-11.

Thanks!
